modLoader="javafml"
loaderVersion="*"
license="All Rights Reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Seaworthy%20Boats"
iconFile="icon.png"

[[mods]]
modId="seaworthyboats"
version="1.1"
displayName="Seaworthy Boats"
displayURL="https://serilum.com/mod/seaworthy-boats"
authors="Serilum"
description='''Reinforce boats into faster, tougher tiers from copper to netherite, and repair them with planks at a shipyard.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Andrean Olgo, AnyankaT, aternosorg, Cherriesaurus, Linda Jansen, MWS, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate Appreciate it! <3   
'''

[[dependencies.seaworthyboats]]
    modId="collective"
    type="required"
    versionRange="[8.40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.seaworthyboats]]
    modId="minecraft"
    type="required"
    versionRange="[26.3]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "seaworthyboats.mixins.json"